### ISSUE TITLE
windowfactory enhancements

### ISSUE THREAD

**Issue by reaby** [eXpansionPluginPack/eXpansion2#101]
- [ ] getGroup($login)   
   * should return the group which login is present
- [ ] closeWindow($login)
   * should close the window for user or group
- [ ] updateWindow($login)
   * should update the window for user or group

**Comment by oliverde8** [comment]
closeWindow : closeManialink 
updateWindow : update

no?

**Comment by reaby** [comment]
from windowfactory doesn't work... says can't find getName() for a string....

**Comment by oliverde8** [comment]
yes they only work with groups.

**Comment by oliverde8** [comment]
We should send manialink by default for action callbacks maybe.

**Comment by reaby** [comment]
That would make sense, since now we need to pass it manually, nearly every actioncallback needs it anyway if need of updating/closing/inteacting manialink.

**Comment by reaby** [comment]
Actually that would solve this issue nicely :)
