### ISSUE TITLE
Gui handler: enable gui content at podium

### ISSUE THREAD

**Issue by reaby** [eXpansionPluginPack/eXpansion2#143]
Currently all gui is disabled during podium.

**Comment by oliverde8** [comment]
Hmm, menu is not displayed during podium? 

Oooo, it's possible that during podium players are not in groups during that period. Because strange events happens during podium with players. 

But I would say Menu should be there because it's on admin groups which shouldn't be affected by this

**Comment by reaby** [comment]
nothing is displayed at podium, i tried to add some podium widgets, but it doesn't draw it

**Comment by oliverde8** [comment]
hmm if you send it to individual player instead of a group does it works then?

**Comment by oliverde8** [comment]
Hmm just tested this and I don't see a bug here

When on podium players switches from player group to specator group so if you show widget to players it's is going to be removed from it's view. 

If you show a ml to all players (see menu) it show well during podium. 

Let me know if you think there is an issue.

**Comment by oliverde8** [comment]
After discussion I close this issue. Feel free to reopen if needed.
