### ISSUE TITLE
Local records don't work on EslTitle Pack

### ISSUE THREAD

**Issue by oliverde8** [eXpansionPluginPack/eXpansion2#287]
## I'm reporting a Bug

eXpansion do'nt recognize EslTitle pack as a TM title pack

### Required information :
- OS : irrelevant
- PHP : irrelevant
- Mysql version : irrelevant 
- Title : ESL
- Game mode : TA

### Explain the expected behavior
Expects to have local records

### Explain the actual behavior
Don't have local records

**Comment by reaby** [comment]
fixed for all titlepacks, see commit f410a1d25a7c8266dee01e2c07f26d6a4debab7b
