### ISSUE TITLE
Update existing widgets so that their positions can be configured

### ISSUE THREAD

**Issue by oliverde8** [eXpansionPluginPack/eXpansion2#318]
## I'm submitting a Feature Request

The system to have widgets position be configurable is done. The docs has been updated as well but all widgets do not adhere to the new methodology. 

http://doc.mp-expansion.com/docs/dev/services/widget_positions.html

Basilly the widgets needs to the fallowing tag : 
```
- {name: expansion.plugin, data_provider: 'exp.widget'}
```

**Comment by reaby** [comment]
fixed at d90eb53c7805253a697bdbe37511e3d2148dff59
