### ISSUE TITLE
[Core]Add a "about/info" window to display server information 

### ISSUE THREAD

**Issue by oliverde8** [eXpansionPluginPack/eXpansion2#389]
See what we had in exp1. No statistics just current information. 

https://github.com/eXpansionPluginPack/eXpansion/blob/master/Core/Gui/Windows/InfoWindow.php

**Comment by reaby** [comment]
How about display less infos for reqular players? For admins it's perhaps good to know much detailed view... like php versions etc...  what you think if re-use the same chat command as vanilla version: /server

For players:
just same chat line as startup the expansion version

For admins:
similar infos as exp1

**Comment by oliverde8** [comment]
So done; with the fallowing features

- Other bundles can add additional data. I am thinking in the feature display number of maps, number of records and such. 
- Permission can be set for each line of information. 
- Using both `/about` and `/server` to display the window. 

![eXpansion - About the server](https://user-images.githubusercontent.com/3658513/76618598-4261ed80-6529-11ea-8ae7-208608f347c8.PNG)

It's not pretty but information is there.
