### ISSUE TITLE
eXpansion don't work with php 7.3 or newer

### ISSUE THREAD

**Issue by BestNoob** [eXpansionPluginPack/eXpansion2#390]
I followed your tutorial for windows i started it, it worked, i shut it down to tweak smth.

And now its running no more also when i use a fresh setup.
And its not creating the mysql database and mysqlsetup.bat cannot find mysql

**Comment by oliverde8** [comment]
Do you have anything in the logs ?

which version of php mysql are you using?

**Comment by BestNoob** [comment]
nothing .......

I also didnt got expansion1 to run (but this was working times before)

I aslo switch composer from my php5.6 installation to php7. 10.4.8-MariaDB, MySQL 5

I reage deleted the stuff xD but i got this output after first succesful run:

```
[2019-11-14 23:00:21] console.ERROR: Error thrown while running command "eXpansion:run -vvv --env=prod -debug". Message: "The "-d" option does not exist." {"error":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): The \"-d\" option does not exist. at XXXXXXXXXXXXXXXXX\\Maniaplanet\\eXpansionV2\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Console\\Input\\ArgvInput.php:126)","command":"eXpansion:run -vvv --env=prod -debug","message":"The \"-d\" option does not exist."} []
[2019-11-14 23:00:21] console.ERROR: Command "eXpansion:run -vvv --env=prod -debug" exited with code "1" {"command":"eXpansion:run -vvv --env=prod -debug","code":1} []
```

**Comment by oliverde8** [comment]
`-debug` is not correct where does that come from it's not in our run scripts

https://github.com/eXpansionPluginPack/eXpansion2/blob/master/bin/run.bat

**Comment by BestNoob** [comment]
> 
> 
> `-debug` is not correct where does that come from it's not in our scripts
> 
> https://github.com/eXpansionPluginPack/eXpansion2/blob/master/bin/run.bat

So this printout was after i deleted the first installation.. i added the -debug .....  so i have no log.

**Comment by oliverde8** [comment]
`-vvv` is there for that it's for verbose which is equivalent

which exact version of php are you using?

**Comment by BestNoob** [comment]
PHP7.3.11

**Comment by oliverde8** [comment]
Confirmed eXpansion won't run on php 7.3 one of our libraries isn't compatible with that particular version.

**Comment by BestNoob** [comment]
> 
> 
> Confirmed eXpansion won't run on php 7.3 one of our libraries isn't compatible with that particular version.

Can you check PHP7.2.24 to ???!! Also there i dont get it to work ..... but i have also the problem with not creating database/tables. https://github.com/eXpansionPluginPack/eXpansion2/issues/391

**Comment by oliverde8** [comment]
Beta4 was released fixing support for php7.2 & 7.3 & 7.4 I am closing this issue
