### ISSUE TITLE
expansion wont create database itself !

### ISSUE THREAD

**Issue by BestNoob** [eXpansionPluginPack/eXpansion2#391]
Under Windows Server  it wont create the databases tables and structures, i had this issue in the past with expansionV1 but in V2 you did not addeed any .sql scheme files to manually create the database !

And the XML schema files as example: LocalMapRatingsBundle-schema.xml **are not working** !!

**Comment by oliverde8** [comment]
I can't reproduce the issue; 

The run scripts provided should run the fallowing commands that will create the database structure. 

```sh
php bin/console propel:migration:diff --env=prod
php bin/console propel:migration:migrate --env=prod
```

If you are running php 7.2 or higher indeed they do not work, update is on it's way to fix it. But that's related to the other issue.

**Comment by oliverde8** [comment]
Beta4 was released I am closing this issue
