### ISSUE TITLE
Menu widget is not sent to players connecting on the server

### ISSUE THREAD

**Issue by oliverde8** [eXpansionPluginPack/eXpansion2#72]

**Comment by reaby** [comment]
Info: 

User groups are generated, but they might not be permanent groups.
Gui handler doesn't find initially following groups: all_players, spectators, players, but players group is generated later. Menu plugin generates new unnamed group for gui handler.

I added some debug infos to console. can be found on latest commit.

**Comment by oliverde8** [comment]
They are persistent groups, if a group has a name it's a persistent group. I will check it should be relatively easy to fix.

**Comment by oliverde8** [comment]
Issue was due to changes made to the PlayerDataProvider; it didn't send PlayerConnect event on start as it used to. 

PlayerDataProvider will properly initialize it self now without sending the event. 

GroupPlugins will individually handle the dispatch of the currently connected players.
