### ISSUE TITLE
Create and enhance Window class

### ISSUE THREAD

**Issue by reaby** [eXpansionPluginPack/eXpansion2#96]
- [x] create uiFactory which is available at window class -> uses uiElements from src/Framework/Gui
- [ ] create DialogWindow, which has default placed buttons for (Apply or Ok or custom) and Cancel buttons.
- [ ] create SimpleDialog, which has Title, Message and OK-button.
- [ ] create AskDialog, which is easy to use from window... has Title, Message and (custom yes) and (custom no) buttons.
- [x] Create context to injectall window & widget dependencies at once
- [x] Remove setMethods on windowFactory services and uses proper DI instead.

**Comment by oliverde8** [comment]
Remaining dialog elements were moved to #126
