### ISSUE TITLE
uiElements

### ISSUE THREAD

**Issue by reaby** [eXpansionPluginPack/eXpansion2#97]
- [x] uiInputbox
- [x] uiTextarea
- [x] uiTooltip which can be added to nearly every uiElement

think of a way to add Tooltips for uiElements, preferably good idea
```php
$button = new uiButton()->setTooltip("asd das");
```

**Comment by oliverde8** [comment]
I would suggest being able to add tooltip anywhere : 
```php
$this->tooltipFactory->createFor($label, 'asd das'));
```

**Comment by reaby** [comment]
uiTooltip is now implemented as following:

```php
$tooltip =  new uiTooltip();
$manialink->addChild($tooltip);

$tooltip->addTooltip($element, "description");
$tooltip->addTooltip($element2, "description2");
```

**Comment by reaby** [comment]
We propably should make ui elements own composer repository ?

1. test coverage drops fast since it need of alot methods
2. other FML users could use the components and maybe contribute new elements as well

**Comment by oliverde8** [comment]
I am repopening this as there is manythings I don't agree on. and to add proper factory around them.
