### ISSUE TITLE
Memory usage 

### ISSUE THREAD

**Issue by reaby** [eXpansionPluginPack/eXpansion2#98]
- [x] memory usage increases 1kb per sec, production environment... event dispatcher problem ?
- [x] closing a window doesn't free as much memory as it took to create window
- [x] Probably an issue with doctrine as well.

**Comment by oliverde8** [comment]
Ooo, second doesen't scare me to much but first one :fearful:

**Comment by reaby** [comment]
indeed, maybe since older php... i tested dev server with php 7.1 - no problem, on test server with php 5.6.30 it keeps increasing...

**Comment by reaby** [comment]
its indeed related to update window contents... so best way to look is gui handler!
i tested... kept server idle for nearly hour and now checked.... it started again when i joined and manialink page updates.

**Comment by reaby** [comment]
first one fixed in d78e115.

**Comment by oliverde8** [comment]
Fixed all issues with GuiHandler creating new ticket for the GridBuilder because windows with GridBuilder don't seem to free all the memory.
